routes/web.php
<?php

/**
 * Global Routes
 * Routes that are used between both frontend and backend
 */

// Switch between the included languages
#Route::get('lang/{lang}', 'LanguageController@swap');

/* ----------------------------------------------------------------------- */

/**
 * FRONTEND Routes
 * Frontend Controllers
 * All route names are prefixed with 'frontend.'
 */
Route::group(['namespace' => 'Frontend'], function () {

    /**
     * Authentication required Routes
     * These frontend controllers require the user to be logged in
     * All route names are prefixed with 'frontend.'
     */
    Route::group(['as' => 'frontend.', 'middleware' => 'auth'], function () {
        /**
         * DIRECT ROUTES - REQUIRE LOGGED
         *  Chat routes
         */

        require(__DIR__ . '/Frontend/User.php');
        require(__DIR__ . '/Frontend/Project.php');
        require(__DIR__ . '/Frontend/Professional.php');
        require(__DIR__ . '/Frontend/Service.php');
        require(__DIR__ . '/Frontend/Quote.php');
        require(__DIR__ . '/Frontend/Comment.php');
        require(__DIR__ . '/Frontend/Media.php');
        require(__DIR__ . '/Frontend/ProjectReview.php');
        require(__DIR__ . '/Frontend/ClientReview.php');
        require(__DIR__ . '/Frontend/Payment.php');
        require(__DIR__ . '/Frontend/Invoice.php');
        require(__DIR__ . '/Frontend/Account.php');
        require(__DIR__ . '/Frontend/Notification.php');
    });




});

/* ----------------------------------------------------------------------- */

/**
 * Backend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Backend', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'admin'], function () {
	/**
	 * These routes need view-backend permission
	 * (good if you want to allow more than one group in the backend,
	 * then limit the backend features by different roles or permissions)
	 *
	 * Note: Administrator has all permissions so you do not have to specify the administrator role everywhere.
	 */
	require (__DIR__ . '/Backend/Dashboard.php');
    require (__DIR__ . '/Backend/Items.php');
    require (__DIR__ . '/Backend/Orders.php');
    require (__DIR__ . '/Backend/Customers.php');
    require (__DIR__ . '/Backend/Logistics.php');
    require (__DIR__ . '/Backend/Pricing.php');
    require (__DIR__ . '/Backend/Suppliers.php');
    require (__DIR__ . '/Backend/Reports.php');
    require (__DIR__ . '/Backend/Tools.php');
    require (__DIR__ . '/Backend/Tickets.php');
    require (__DIR__ . '/Backend/Calc.php');
    require (__DIR__ . '/Backend/Access.php');
    require (__DIR__ . '/Backend/Account.php');
    require (__DIR__ . '/Backend/Category.php');
	require (__DIR__ . '/Backend/Search.php');
    require (__DIR__ . '/Backend/Credits.php');
    require (__DIR__ . '/Backend/Links.php');
	require (__DIR__ . '/Backend/LogViewer.php');
});


/**
 * PUBLIC ROUTES
 */

Route::group(['namespace' => 'Frontend'], function () {

    #Core jazz... dont mess with it for now
    require(__DIR__ . '/Frontend/Access.php');


    Route::group(['as' => 'public.'], function () {

        Route::get('/', 'FrontendController@index')->name('index');

        require(__DIR__ . '/Public/Pages.php');

        require(__DIR__ . '/Public/Category.php');
        require(__DIR__ . '/Public/User.php');
        require(__DIR__ . '/Public/ProjectReview.php');
        require(__DIR__ . '/Public/Professionals.php');
        require(__DIR__ . '/Public/Projects.php');
        require(__DIR__ . '/Public/Services.php');

    });

});

app/Models/Quote/Traits/Attribute/QuoteAttribute.php
<?php

namespace App\Models\Quote\Traits\Attribute;
use App\Helpers\Helper;
use Illuminate\Support\Facades\Request;

/**
 * Class UserAttribute
 * @package App\Models\Access\User\Traits\Attribute
 */
trait QuoteAttribute
{

    protected $route_prefix = 'frontend';

    protected $status_keys = [
        0 => 'draft',
        1 => 'sent',
        2 => 'read',
        3 => 'hired',
        4 => 'unsuccessful',
        5 => 'reviewed',
        6 => 'interacted',
        7 => 'request_hired',
    ];

    private function __construct() {
        $this->getRoutePrefix();
    }

    /**
     * If passed a ID returns the specific status name.
     * If passed a status name it will return the status key
     * @param $find
     * @return mixed
     */
    public function getStatusKey($find) {
        if (is_numeric($find)) {
            return $this->status_keys[$find];
        } else {
            return array_search($find, $this->status_keys);
        }
    }
	/**
	 * @return string
	 */
    public function getStatusLabelAttribute()
    {

        switch ($this->status) {
            case 0:
                #Draft pending Credits purchase
                return "<span data-toggle='popover' data-content='".trans('strings.frontend.quotes.status.'.access()->group().'.draft_description')."' title='Draft Status' class='label label-danger'>Draft</span>";
                break;

            case 1:
                return "<span data-toggle='popover' data-content='".trans('strings.frontend.quotes.status.'.access()->group().'.sent_description')."' title='Sent Status' class='label label-warning'>Sent</span>";
                break;

            case 2:
                return "<span data-toggle='popover' data-content='".trans('strings.frontend.quotes.status.'.access()->group().'.read_description')."' title='Read Status' class='label label-info'>Read</label>";
                break;

            case 3:
                return "<span data-toggle='popover' data-content='".trans('strings.frontend.quotes.status.'.access()->group().'.hired_description')."' title='Hired Status' class='label label-success'><i class='fa fa-handshake-o'></i> Hired</span>";
                break;

            case 4:
                return "<span data-toggle='popover' data-content='".trans('strings.frontend.quotes.status.'.access()->group().'.unsuccessful_description')."' title='Unsuccessful Status' class='label label-danger'>Unsuccessful</span>";
                break;

            case 5:
                return "<span data-toggle='popover' data-content='".trans('strings.frontend.quotes.status.'.access()->group().'.reviewed_description')."' title='Reviewed Status' class='label label-success'><i class='fa fa-handshake-o'></i> Reviewed</span>";
                break;

            case 6:
                return "<span data-toggle='popover' data-content='".trans('strings.frontend.quotes.status.'.access()->group().'.interacted_description')."' title='Interacted Status' class='label label-info'>Interacted</span>";
                break;

            case 7:
                #if this is professional
                if(access()->id() == $this->user_id) {
                    return "<span data-toggle='popover' data-content='".trans('strings.frontend.quotes.status.'.access()->group().'.request_hired_description')."' title='Pending Hire Status' class='label label-info'>Pending Hire</span>";
                } else {
                    #else client
                    return "<span data-toggle='popover' data-content='".trans('strings.frontend.quotes.status.'.access()->group().'.request_hired_description')."' title='Confirm Hire Status' class='label label-danger'>Confirm Hire?</span>";
                }

                break;
        }
    }

    public function getPriceLabelAttribute()
    {
        if ($this->need_more_info) {
            return '<div data-toggle="popover" data-content="Professional needs more information in order to quote you" class="badge label-warning"><i class="fa fa-question-circle"></i> more info</div>';
        } else {
            return '<div class="text-bold">'.Helper::formatPrice($this->price).' '.trans('strings.frontend.quotes.price_types.'.$this->price_type).'</div>';
        }

    }

    public function getRoutePrefix() {
        if (Request::is('*admin*')) {
            $this->route_prefix = 'admin';
        }
    }

    /**
     * @return string
     */
    public function getEditButtonAttribute()
    {
        #Only allow edit of Quote before client has read it.
        if ($this->status < 2) {
            #Go to quote/edit on BACKEND
            if ($this->route_prefix == 'admin') {
                return '<a href="' . route($this->route_prefix . '.quote.edit', $this) . '" class="btn btn-sm btn-primary"><i class="fa fa-pencil" data-toggle="popover" data-trigger="hover" data-placement="top" title="' . trans('buttons.general.crud.edit') . '"></i></a> ';
            } else {
                #Go to project page
                return '<a href="' . route($this->route_prefix . '.project.show', [$this->project_id, 'quote_id'=>$this->id]) . '" class="btn btn-sm btn-primary"><i class="fa fa-pencil" data-toggle="popover" data-trigger="hover" data-placement="top" title="' . trans('buttons.general.crud.edit') . '"></i></a> ';
            }
        }
    }

    /**
     * @return string
     */
    public function getStatusButtonAttribute()
    {
        if ($this->user_id != access()->id()) {
            switch ($this->status) {
                case 0:
                    return '<a href="' . route($this->route_prefix.'.quote.mark', [
                        $this,
                        1
                    ]) . '" class="btn btn-sm btn-success"><i class="fa fa-play" data-toggle="popover" data-trigger="hover" data-placement="top" title="' . trans('buttons.backend.quotess.activate') . '"></i></a> ';
                // No break

                case 1:
                    return '<a href="' . route($this->route_prefix.'.quote.mark', [
                        $this,
                        0
                    ]) . '" class="btn btn-sm btn-warning"><i class="fa fa-pause" data-toggle="popover" data-trigger="hover" data-placement="top" title="' . trans('buttons.backend.quotess.deactivate') . '"></i></a> ';
                // No break

                default:
                    return '';
                // No break
            }
        }

        return '';
    }

    /**
     * @return string
     */
    public function getDeleteButtonAttribute()
    {
        if ($this->route_prefix == 'admin') {
            return '<a href="' . route($this->route_prefix.'.quote.destroy', $this) . '"
                 data-method="delete"
                 data-trans-button-cancel="' . trans('buttons.general.cancel') . '"
                 data-trans-button-confirm="' . trans('buttons.general.crud.delete') . '"
                 data-trans-title="' . trans('strings.backend.general.are_you_sure') . '"
                 class="btn btn-sm btn-danger"><i class="fa fa-trash" data-toggle="popover" data-trigger="hover" data-placement="top" title="' . trans('buttons.general.crud.delete') . '"></i></a> ';
        }

        return '';
    }

    public function getShowButtonAttribute()
    {
        if ($this->route_prefix == 'admin')
            return '<a href="' . route($this->route_prefix.'.quote.show', $this) . '" class="btn btn-sm btn-info"><i class="fa fa-search" data-toggle="popover" data-trigger="hover" data-placement="top" title="' . trans('buttons.general.crud.view') . '"></i></a> ';
    }

	/**
     * @return string
     */
    public function getRestoreButtonAttribute()
    {
        return '<a href="' . route($this->route_prefix.'.quote.restore', $this) . '" name="restore_user" class="btn btn-sm btn-info"><i class="fa fa-refresh" data-toggle="popover" data-trigger="hover" data-placement="top" title="' . trans('buttons.backend.quotess.restore_user') . '"></i></a> ';
    }

	/**
     * @return string
     */
    public function getDeletePermanentlyButtonAttribute()
    {
        return '<a href="' . route($this->route_prefix.'.quote.delete-permanently', $this) . '" name="delete_user_perm" class="btn btn-sm btn-danger"><i class="fa fa-trash" data-toggle="popover" data-trigger="hover" data-placement="top" title="' . trans('buttons.backend.quotess.delete_permanently') . '"></i></a> ';
    }


    public function getMarkHiredButtonAttribute()
    {
        if ($this->status == 2 || $this->status == 6)
            return '<a data-toggle="popover" data-trigger="hover" data-content="Marking this quote as hired will send a notification to client to confirm this." id="qt-btn-'.$this->id.'" href="javascript:void(0)" onclick="MarkQuoteHired('.$this->id.', this)" class="btn btn-success btn-sm"><i class="fa fa-handshake-o"></i> Mark as Hired</a> ';
    }

    public function isPending()
    {
        if ($this->status == 1 || $this->status == 2 || $this->status == 6) {
            return true;
        } else {
            return false;
        }
    }



    /**
     * @return string
     */
    public function getActionButtonsAttribute()
    {
        if ($this->trashed()) {
            return $this->getRestoreButtonAttribute() .
                $this->getDeletePermanentlyButtonAttribute();
        }

        return
			$this->getEditButtonAttribute() .
            $this->getShowButtonAttribute() .
            $this->getMarkHiredButtonAttribute() .
            $this->getStatusButtonAttribute() .
            $this->getDeleteButtonAttribute();
    }
}

app/Models/Quote/Traits/QuoteAccess.php
<?php

namespace App\Models\Quote\Traits;

/**
 * Class UserAccess
 * @package App\Models\Access\User\Traits
 */
trait QuoteAccess
{

}

app/Http/Controllers/Api/Quote/ApiQuoteController.php
<?php

namespace App\Http\Controllers\Api\Quote;

use App\Http\Controllers\Controller;
use App\Models\Quote\Quote;
use App\Repositories\Backend\Quote\QuoteRepository;

class ApiQuoteController extends Controller
{

    public function __construct(QuoteRepository $quotes)
    {
        $this->quotes = $quotes;
    }


    public function hired(Quote $quote)
    {
        /**
         * NO other quotes have been Hired
         * 1 sent
         * 2 read
         * 6 interacted
         */
        if ($quote->status == 2 || $quote->status == 1 || $quote->status == 6 || $quote->status == 7) {
            /**
             * if Logged in user is CLIENT
             */
            if (access()->id() && access()->id() == $quote->project->user_id) {

                $quote = $this->quotes->hired($quote);
                return response([
                    'status'=> 'success',
                    'data' => [
                        'type' => 'hired'
                    ],
                    'message'=> 'Quote was marked as hired'
                ], 200);
            } elseif (access()->id() && access()->id() == $quote->user_id) {

                /**
                 * if Logged in user is Professional (requesting hire)
                 */
                $quote = $this->quotes->verify_hired($quote);

                return response([
                    'status'=> 'success',
                    'data' => [
                        'type' => 'verify_hire'
                    ],
                    'message'=> 'Quote was marked as hired'
                ], 200);
            }
        }

        return response([
            'status'=> 'error',
            'message'=> 'Error occurred'
        ], 200);
    }

}

app/Http/Controllers/Backend/Quote/QuoteController.php
<?php

namespace App\Http\Controllers\Backend\Quote;

use App\Http\Requests\Backend\Quote\StoreQuoteRequest;
use App\Models\Category\Category;
use App\Repositories\Backend\Quote\QuoteRepository;
use App\Http\Requests\Backend\Quote\ManageQuoteRequest;
use App\Models\Quote\Quote;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\App;
use App\Quotes\Images\Images;
use App\Helpers\Helper;

class QuoteController extends Controller
{

    protected $quotes;

    /**
     * @param QuoteRepository $quotes
     */
    public function __construct(QuoteRepository $quotes)
    {
        $this->quotes = $quotes;
    }

    //
    public function index()
    {
        return view('backend.quote.index');
    }

    public function show(Quote $quote, ManageQuoteRequest $request) {
        return view('backend.quote.show')
            ->withQuote($quote);
    }

    public function edit(Quote $quote, ManageQuoteRequest $request)
    {
        $categories = Helper::make_tree_array(Category::get()->toArray(),'parent_id');

        return view('backend.quote.edit')
            ->withQuote($quote)
            ->withCategories($categories);
    }

    public function create(ManageQuoteRequest $request)
    {
        $categories = Helper::make_tree_array(Category::get()->toArray(),'parent_id');

        return view('backend.quote.create')
            ->withCategories($categories);
    }

    public function update(Quote $quote, ManageQuoteRequest $request)
    {

        $data = $request->all();

        if ($imagename = Images::upload($request, ['image', $quote->getTable()])) {
            $data['image'] = $imagename['image'];
        } else {
            #If no image then exclude image from update value array
            unset($data['image']);
        }

        $this->quotes->update($quote, ['data' => $data]);
        return redirect()->route('admin.quote.index')->withFlashSuccess('Update success');
    }

    public function store(StoreQuoteRequest $request)
    {

        $data = $request->all();

        if ($imagename = Images::upload($request, ['image', (new Quote)->getTable()])) {
            $data['image'] = $imagename['image'];
        }

        #past request data to save
        $this->quotes->create(['data' => $data]);
        return redirect()->route('admin.quote.index')->withFlashSuccess('Item Created');
    }

    public function destroy(Quote $quote, ManageQuoteRequest $request)
    {
        $this->quotes->delete($quote);
        return redirect()->route('admin.quote.deleted')->withFlashSuccess('Item Deleted');
    }
}

resources/views/frontend/quote/includes/details.blade.php
@if ($quote->status == 7)
    <div class="alert alert-warning">
        <h4 class="no-top-margin"><i class="fa fa-question-circle-o"></i> Confirm Hire</h4>
        <p>{{ trans('strings.frontend.quotes.status.'.access()->group().'.request_hired_description') }}</p>
    </div>
@endif

<div class="row">
    <div class="col-xs-12">
        <h2 id="quote_heading" class="qt_heading no-top-margin pull-left"><i class="fa fa-address-card"></i> Quote </h2>
        <div class="qt_label label pull-left btn-lg">QT0{{ $quote->id }}</div>
        <div class="qt_label pull-left">{!! $quote->status_label !!}</div>
        <div class="pull-right">
            Sent: {{ $quote->created_at->format(config('app.date.long_min')) }}
        </div>
    </div>
</div>

<div class="jumbotron">
    <div class="jumbotron-contents">
        <div class="row">


            <div class="col-sm-7">
                @include('frontend.professional.includes.mini_profile', ['professional' => $quote->professional])
            </div>

            <div class="col-sm-5 text-right">
                <div class="h4"><i class="fa fa-phone-square"></i> {{ $quote->professional->telephone }}</div>
                @if($quote->professional->company_email)
                <div><i class="fa fa-envelope-square"></i> <a target="_blank" href="mailto:{{ $quote->professional->company_email }}">Email Address</a></div>
                @endif
            </div>
        </div>

        <hr>


        <div class="quote_avatar chat-image pull-left">
            {!! $quote->user->getImageHtml('thumb', 'avatar-med img-circle') !!}<br/>
            Written by,<br/>
            <b>{{ $quote->user->name }} {!! $quote->user->online_label !!}</b>
        </div>
        <div class="card-body quote-message">
            <h5 class="no-top-margin">Quote Details:</h5>
            <p>{!! $quote->description !!}</p>

            @if($quote->media->count())
            <div class="quote_attachments clearfix">
                <div class="h6"><i class="fa fa-paperclip"></i> Attachments</div>

                @include('frontend.media.includes.partials.gallery', ['media' => $quote->media])

            </div>
            @endif

        </div>
        <div class="clearfix"></div>

        <div class="text-center {{ $quote->need_more_info?'bg-warning':'' }}">
            <hr>
            <div class="h5">Estimated Price:</div>
            <div class="h1 quoteprice ">
                {!! Helper::formatPrice($quote->price) !!} <span>{!!  trans('strings.frontend.quotes.price_types.'.$quote->price_type) !!}</span>
                @if($quote->need_more_info)
                    <br/>
                    <div data-toggle="popover" data-content="The professional has indicated that he is unable to estimate your project. Please be in contact in order to answer any questions he has." class="badge btn-lg label-primary"><i class="fa fa-question-circle-o"></i> Require more information</div>
                @endif
            </div>
        </div>



        @if($quote->project->status != 4 && $quote->project->status != 3)

            <div class="tip quote_actions">
            @if($quote->user_id == access()->id())

                <div class="h5 no-top-margin">Quote Status: {!!  $quote->StatusLabel !!}</div>

                @if($quote->status != 4)
                <table width="100%">
                    <tr>
                    <td align="center"><a class="btn btn-primary" href="#messages_heading"><i class="fa fa-reply"></i> Reply</a></td>
                    @if($quote->status == 7)
                            <td align="center"><div class="alert alert-warning"><i class="fa fa-hourglass-2"></i> Waiting for client to confirm hire</div></td>
                    @elseif($quote->status == 3)
                        <td align="center"><div class="alert alert-info"><i class="fa fa-hourglass-2"></i> Waiting for client review</div></td>
                    @else
                        @php($title = "This will send a notification to the client to confirm the hire.")

                        <td align="center"><a class="btn btn-success" id="qt-btn-{{ $quote->id }}" data-toggle="popover" data-trigger="hover" data-content="{{ $title }}" href="javascript:void(0)" onclick="MarkQuoteHired({{ $quote->id }}, this)" ><i class="fa fa-handshake-o"></i> Mark as Hired</a></td>
                    @endif
                    </tr>
                </table>
                @endif
            @elseif(access()->id() == $quote->project->user_id)

                @php($title = "This will mark the project as \"hired\" allowing you to review the professional's work once done.")


                    <table width="100%">
                        <tr>
                        @if($quote->status == 1 || $quote->status == 2 || $quote->status == 6)
                        <td align="center"><a class="btn btn-default" href="#messages_heading"><i class="fa fa-reply"></i> Reply</a></td>
                        @endif
                        @if($quote->hired)
                            @if ($quote->status == 3)
                                <td align="center"><a id="qt-btn-{{ $quote->id }}" href="{{ route('frontend.quote.project_review.create', $quote->id) }}" class="btn btn-info"><i class="fa fa-pencil-square"></i> Review Work</a></td>
                            @endif
                        @else
                            <td align="center"><a class="btn btn-success" id="qt-btn-{{ $quote->id }}" data-toggle="popover" data-trigger="hover" data-content="{{ $title }}" href="javascript:void(0)" onclick="MarkQuoteHired({{ $quote->id }}, this)" ><i class="fa fa-handshake-o"></i> {{ $quote->status == 7?'Confirm Hire':'Mark as Hired' }}</a></td>
                        @endif
                        @if ($quote->status == 1 || $quote->status == 2 || $quote->status == 6 || $quote->status == 7)
                            <td align="center"><a class="btn btn-danger" data-toggle="firemodal" href="{{ route('frontend.quote.decline', $quote->id) }}"><i class="fa fa-thumbs-down"></i> Decline</a></td>
                        @endif
                        </tr>
                    </table>


            @endif
            </div>

        @endif



    </div>
</div>


@if($quote->status == 5 && $quote->review)
    <div class="jumbotron">
        <div class="jumbotron-contents">
            <h4 id="reviews_heading" class="no-top-margin">Client Review</h4>

            @include('frontend.project_review.include.review', ['review' => $quote->review])

            @if ($quote->client_review)
                <hr>
                <div class="">
                    <div class="h5">Professional Review</div>
                @include('frontend.client_review.include.review', ['review' => $quote->client_review])
                </div>
            @else
                @if($quote->review && $quote->user_id == access()->id())
                    <div class="heading_btn">
                        <a class="btn btn-info" href="{{ route('frontend.quote.client_review.create', $quote->id) }}"><i class="fa fa-pencil-square-o"></i> Review Client</a>
                    </div>
                @endif
            @endif
        </div>
    </div>
@endif

@php($disable_add = 0)
@php($disable_first_comment = 0)

@if($quote->status == 4 || $quote->project->status == 4 || $quote->project->status == 3)
    @php($disable_add = 1)
@endif
@if($quote->user_id == $logged_in_user->id)
    @php($disable_first_comment = 1)
@endif
<div class="row">
    <div class="col-xs-12">
        <h2 id="messages_heading" class="no-top-margin pull-left"><i class="fa fa-comment"></i> Messages</h2>
    </div>
</div>

<div>
    @include('frontend.comments.discuss', ['model'=>'quote', 'id'=>$quote->id, 'disable_add' => $disable_add, 'disable_first_comment' => $disable_first_comment])
</div>