routes/web.php
<?php

/**
 * Global Routes
 * Routes that are used between both frontend and backend
 */

// Switch between the included languages
#Route::get('lang/{lang}', 'LanguageController@swap');

/* ----------------------------------------------------------------------- */

/**
 * FRONTEND Routes
 * Frontend Controllers
 * All route names are prefixed with 'frontend.'
 */
Route::group(['namespace' => 'Frontend'], function () {

    /**
     * Authentication required Routes
     * These frontend controllers require the user to be logged in
     * All route names are prefixed with 'frontend.'
     */
    Route::group(['as' => 'frontend.', 'middleware' => 'auth'], function () {
        /**
         * DIRECT ROUTES - REQUIRE LOGGED
         *  Chat routes
         */

        require(__DIR__ . '/Frontend/User.php');
        require(__DIR__ . '/Frontend/Project.php');
        require(__DIR__ . '/Frontend/Professional.php');
        require(__DIR__ . '/Frontend/Service.php');
        require(__DIR__ . '/Frontend/Quote.php');
        require(__DIR__ . '/Frontend/Comment.php');
        require(__DIR__ . '/Frontend/Media.php');
        require(__DIR__ . '/Frontend/ProjectReview.php');
        require(__DIR__ . '/Frontend/ClientReview.php');
        require(__DIR__ . '/Frontend/Payment.php');
        require(__DIR__ . '/Frontend/Invoice.php');
        require(__DIR__ . '/Frontend/Account.php');
        require(__DIR__ . '/Frontend/Notification.php');
    });




});

/* ----------------------------------------------------------------------- */

/**
 * Backend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Backend', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'admin'], function () {
	/**
	 * These routes need view-backend permission
	 * (good if you want to allow more than one group in the backend,
	 * then limit the backend features by different roles or permissions)
	 *
	 * Note: Administrator has all permissions so you do not have to specify the administrator role everywhere.
	 */
	require (__DIR__ . '/Backend/Dashboard.php');
    require (__DIR__ . '/Backend/Items.php');
    require (__DIR__ . '/Backend/Orders.php');
    require (__DIR__ . '/Backend/Customers.php');
    require (__DIR__ . '/Backend/Logistics.php');
    require (__DIR__ . '/Backend/Pricing.php');
    require (__DIR__ . '/Backend/Suppliers.php');
    require (__DIR__ . '/Backend/Reports.php');
    require (__DIR__ . '/Backend/Tools.php');
    require (__DIR__ . '/Backend/Tickets.php');
    require (__DIR__ . '/Backend/Calc.php');
    require (__DIR__ . '/Backend/Access.php');
    require (__DIR__ . '/Backend/Account.php');
    require (__DIR__ . '/Backend/Category.php');
	require (__DIR__ . '/Backend/Search.php');
    require (__DIR__ . '/Backend/Credits.php');
    require (__DIR__ . '/Backend/Links.php');
	require (__DIR__ . '/Backend/LogViewer.php');
});


/**
 * PUBLIC ROUTES
 */

Route::group(['namespace' => 'Frontend'], function () {

    #Core jazz... dont mess with it for now
    require(__DIR__ . '/Frontend/Access.php');


    Route::group(['as' => 'public.'], function () {

        Route::get('/', 'FrontendController@index')->name('index');

        require(__DIR__ . '/Public/Pages.php');

        require(__DIR__ . '/Public/Category.php');
        require(__DIR__ . '/Public/User.php');
        require(__DIR__ . '/Public/ProjectReview.php');
        require(__DIR__ . '/Public/Professionals.php');
        require(__DIR__ . '/Public/Projects.php');
        require(__DIR__ . '/Public/Services.php');

    });

});

app/Models/Professional/Traits/Attribute/ProfessionalAttribute.php
<?php

namespace App\Models\Professional\Traits\Attribute;


use App\Helpers\Helper;

trait ProfessionalAttribute
{

    public function getStatusLabelAttribute()
    {
        switch ($this->status) {
            case 0:
                #Pending approval
                return "<span title='Pending Status' class='badge label-warning' >Pending</span>";
                break;

            case 1:
                #Active
                return "<span title='Active Status' class='badge label-success'>Active</span>";
                break;

            case 2:
                #unconfirmed
                return "<span title='Unconfirmed' class='badge label-warning'>Unconfirmed</span>";
                break;
        }
    }

    public function getVerify($style = 'icon') {
        if ($this->verify_status) {
            switch ($style) {
                case 'icon':
                    return '<span data-toggle="popover" data-title="Verified Professional" data-content="' . $this->title . ' has been verified by ' . config('app.name') . '." class="pro_verify_icon fa-stack fa-lg">
                        <i class="fa fa-circle fa-stack-2x"></i>
                        <i class="fa fa-check fa-stack-1x fa-inverse"></i>
                        </span>';
                    break;
                case 'big':
                    return '<div class="badge label-primary"><i class="fa fa-check"></i> VERIFIED</div>';
                    break;
            }

            return '<span data-toggle="popover" data-title="Verified Professional" data-content="' . $this->title . ' has been verified by ' . config('app.name') . '." class="pro_verify_icon fa-stack fa-lg">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fa fa-check fa-stack-1x fa-inverse"></i>
            </span>';
        }

        return '';
    }

    public function getVerifyLabelAttribute()
    {
        if ($this->verify_status) {

            return $this->getVerify('icon');
        }
        return '';
    }

    /**
     * @return bool
     */
    public function isActive() {
        return $this->status == 1;
    }

    /**
     * @return string
     */
    public function getApprovedLabelAttribute()
    {
        if ($this->isApproved())
            return "<i class='text-success fa fa-thumbs-up fa-lg'></i>";
        return "<i class='text-gray fa fa-remove fa-lg'></i>";
    }

    public function getVerifiedLabelAttribute()
    {
        if ($this->verify_status)
            return "<i class='text-success fa fa-check-circle fa-lg'></i>";
        return "<i class='text-gray fa fa-remove fa-lg'></i>";
    }

    public function getOverallRatingStarsAttribute()
    {

        $rating = round($this->rating_overall_tot, 1);

        if ($rating) {
            return Helper::showStars($rating);
        } else {
            return '<span data-toggle="popover" data-content="This professional has not yet been rated on '.config('app.name').'." class="badge label-default">no ratings</span>';
        }
    }

    public function getLogoHtml($size='sm', $embed = false) {
        if ($this->logo && file_exists(public_path('/images/'.$this->table.'/thumbnail/'.$this->logo))) {
            if ($embed) {
                return '<img alt="'.$this->title.'" src="'.public_path('/images/'.$this->table.'/thumbnail/'.$this->logo).'" />';
            }
            return '<div class="pro-logo-cell logo-container '.$size.'-square" style="background-image:url(/images/'.$this->table.'/thumbnail/'.$this->logo.')"></div>';
        } else {
            if ($embed) {
                return '<div style="border-radius: 50%;width: 180px;height: 180px;line-height: 180px;font-size: 60px;display: inline-block;font-weight: 700;white-space: nowrap;text-align: center;color: #fff;background-color:'.Helper::genColorCodeFromText($this->title).'">'.Helper::createAcronym($this->title).'</div>';
            }
            return '<div class="img-circle logo-string '.$size.'-square" style="background-color:'.Helper::genColorCodeFromText($this->title).'">'.Helper::createAcronym($this->title).'</div>';
        }
    }

    public function getThumbUrlAttribute() {
        return asset('/images/'.$this->table.'/thumbnail/'.$this->logo);
    }

    public function getLogoUrlAttribute() {
        if ($this->logo)
            return asset('/images/'.$this->table.'/'.$this->logo);
    }

    public function getHeroImageUrlAttribute() {
        if ($this->hero_image)
            return asset('/images/'.$this->table.'/'.$this->hero_image);
    }

    /**
     * @return bool
     */
    public function isApproved() {
        return $this->approved == 1;
    }

    /**
     * @return string
     */
    public function getEditButtonAttribute()
    {
        return '<a href="' . route('admin.professional.edit', $this) . '" class="btn btn-sm btn-primary"><i class="fa fa-pencil" data-toggle="popover" data-trigger="hover" data-placement="top" title="' . trans('buttons.general.crud.edit') . '"></i></a> ';
    }

    /**
     * @return string
     */
    public function getStatusButtonAttribute()
    {
        switch ($this->status) {
            case 0:
                return '<a href="' . route('admin.professional.mark', [
                    $this,
                    1
                ]) . '" class="btn btn-sm btn-success"><i class="fa fa-play" data-toggle="popover" data-trigger="hover" data-placement="top" title="' . trans('buttons.backend.general.activate') . '"></i></a> ';
            // No break

            case 1:
                return '<a href="' . route('admin.professional.mark', [
                    $this,
                    0
                ]) . '" class="btn btn-sm btn-warning"><i class="fa fa-pause" data-toggle="popover" data-trigger="hover" data-placement="top" title="' . trans('buttons.backend.general.deactivate') . '"></i></a> ';
            // No break

            default:
                return '';
            // No break
        }

        return '';
    }

    /**
     * @return string
     */
    public function getApprovedButtonAttribute()
    {
        switch ($this->approved) {
            case 0:
                return '<a href="' . route('admin.professional.approve', [
                    $this,
                    1
                ]) . '" class="btn btn-sm btn-success"><i class="fa fa-thumbs-up" data-toggle="popover" data-trigger="hover" data-placement="top" title="Approve Item"></i></a> ';
            // No break

            case 1:
                return '<a href="' . route('admin.professional.approve', [
                    $this,
                    0
                ]) . '" class="btn btn-sm btn-danger"><i class="fa fa-thumbs-down" data-toggle="popover" data-trigger="hover" data-placement="top" title="Un-Approve item"></i></a> ';
            // No break

            default:
                return '';
            // No break
        }

        return '';
    }

    public function getVerifiedButtonAttribute()
    {
        switch ($this->verify_status) {
            case 0:
                return '<a href="' . route('admin.professional.verify', [
                    $this,
                    1
                ]) . '" class="btn btn-sm btn-success"><i class="fa fa-check-circle" data-toggle="popover" data-trigger="hover" data-placement="top" title="Verify Professional"></i></a> ';
            // No break

            case 1:
                return '<a href="' . route('admin.professional.verify', [
                    $this,
                    0
                ]) . '" class="btn btn-sm btn-danger"><i class="fa fa-remove" data-toggle="popover" data-trigger="hover" data-placement="top" title="Remove Verified"></i></a> ';
            // No break

            default:
                return '';
            // No break
        }

        return '';
    }

    /**
     * @return string
     */
    public function getDeleteButtonAttribute()
    {

        return '<a href="' . route('admin.professional.destroy', $this) . '"
             data-method="delete"
             data-trans-button-cancel="' . trans('buttons.general.cancel') . '"
             data-trans-button-confirm="' . trans('buttons.general.crud.delete') . '"
             data-trans-title="' . trans('strings.backend.general.are_you_sure') . '"
             class="btn btn-sm btn-danger"><i class="fa fa-trash" data-toggle="popover" data-trigger="hover" data-placement="top" title="' . trans('buttons.general.crud.delete') . '"></i></a> ';

    }

    public function getShowButtonAttribute()
    {
        return '<a href="' . route('admin.professional.show', $this) . '" class="btn btn-sm btn-info"><i class="fa fa-search" data-toggle="popover" data-trigger="hover" data-placement="top" title="' . trans('buttons.general.crud.view') . '"></i></a> ';
    }

	/**
     * @return string
     */
    public function getRestoreButtonAttribute()
    {
        return '<a href="' . route('admin.professional.restore', $this) . '" name="restore_item" class="btn btn-sm btn-info"><i class="fa fa-refresh" data-toggle="popover" data-trigger="hover" data-placement="top" title="' . trans('buttons.backend.general.restore') . '"></i></a> ';
    }

	/**
     * @return string
     */
    public function getDeletePermanentlyButtonAttribute()
    {
        return '<a href="' . route('admin.professional.delete-permanently', $this) . '" name="delete_item_perm" class="btn btn-sm btn-danger"><i class="fa fa-trash" data-toggle="popover" data-trigger="hover" data-placement="top" title="' . trans('buttons.backend.general.delete_permanently') . '"></i></a> ';
    }

    /**
     * @return string
     */
    public function getActionButtonsAttribute()
    {
        if ($this->trashed()) {
            return $this->getRestoreButtonAttribute() .
                $this->getDeletePermanentlyButtonAttribute();
        }

        return
			$this->getEditButtonAttribute() .
            $this->getShowButtonAttribute() .

app/Models/Professional/Traits/ProfessionalAccess.php
<?php

namespace App\Models\Professional\Traits;

/**
 * Class UserAccess
 * @package App\Models\Access\User\Traits
 */
trait ProfessionalsAccess
{

}

app/Http/Controllers/Api/Professional/ApiProfessionalController.php
<?php

namespace App\Http\Controllers\Api\Professional;

use App\Http\Controllers\Controller;
use App\Models\Professional\Professional;
use Illuminate\Http\Request;

/**
 * Class DashboardController
 * @package App\Http\Controllers\Frontend
 */
class ApiProfessionalController extends Controller
{

    public function search(Request $request)
    {

        if ($request->input('string')) {
            $professionals = Professional::select('title', 'slug', 'id')->where('title', 'LIKE', $request->input('string').'%')
                ->orderBy('title', 'asc')
                ->limit(10)->get()->toArray();

            return response()->json($professionals);
        }


    }

}

app/Http/Controllers/Backend/Professional/ProfessionalTableController.php
<?php

namespace App\Http\Controllers\Backend\Professional;

use App\Http\Controllers\Controller;
use Yajra\Datatables\Facades\Datatables;
use App\Repositories\Backend\Professional\ProfessionalRepository;
use App\Http\Requests\Backend\Professional\ManageProfessionalRequest;

/**
 * Class UserTableController
 */
class ProfessionalTableController extends Controller
{
	/**
	 * @var UserRepository
	 */
	protected $professional;

	/**
	 * @param UserRepository $users
	 */
	public function __construct(ProfessionalRepository $professionals)
	{
		$this->professionals = $professionals;
	}

	/**#
	 * @return mixed
	 */
	public function __invoke(ManageProfessionalRequest $request) {
	    if (!isset($request->approved))
            $request->approved = 1;

		return Datatables::of($this->professionals->getForDataTable($request->status, $request->trashed, $request->approved))
            ->addColumn('actions', function($professional) {
                return $professional->action_buttons;
            })
            ->addColumn('status', function($professional) {
                return $professional->status_label;
            })
            ->addColumn('image_html', function($professional) {
                return $professional->image_html;
            })
			->withTrashed()
			->make(true);
	}
}

app/Http/Controllers/Frontend/Professional/ProfessionalQuotesController.php
<?php

namespace App\Http\Controllers\Frontend\Professional;

use App\Http\Requests\Frontend\Professional\ManageProfessionalRequest;
use App\Http\Requests\Frontend\Professional\StoreProfessionalRequest;
use App\Http\Requests\Frontend\Professional\UpdateProfessionalRequest;
use App\Models\Access\User\User;
use App\Models\Category\Category;
use App\Repositories\Backend\Professional\ProfessionalRepository;
use App\Models\Professional\Professional;
use App\Services\MediaManager\MediaManager;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\App;
use App\Services\Images\Images;
use Illuminate\Support\Facades\Notification;

class ProfessionalQuotesController extends Controller
{

    protected $professionals;

    /**
     * @param ProfessionalRepository $professionals
     */
    public function __construct(ProfessionalRepository $professionals)
    {
        $this->professionals = $professionals;
    }

    public function quotes(Professional $professional, $status = 'pending') {

        switch ($status) {
            case "draft":
                $quotes = $professional->draft_project_quotes()->paginate(15);
                break;
            case "pending":
                $quotes = $professional->open_project_quotes()->paginate(15);
                break;
            case "hired":
                $quotes = $professional->hired_project_quotes()->paginate(15);
                break;
            case "unsuccessful":
                $quotes = $professional->unsuccessful_project_quotes()->paginate(15);
                break;
        }

        return view('frontend.professional.quotes')
            ->with(compact('professional', 'quotes', 'status'));
    }

}

resources/views/frontend/professional/includes/branch_fields.blade.php
<h4>Branch</h4>

<div class="form-group">
    {{ Form::label('branch[branch_title]', 'Branch Specific Name (OPTIONAL)', ['class' => 'col-lg-2 control-label']) }}
    <div class="col-lg-10">
        {{ Form::text('branch[branch_title]', null, ['class' => 'form-control', 'placeholder' => 'Defaults to title']) }}
        <div class="help-block with-errors"></div>
    </div><!--col-lg-10-->
</div><!--form control-->

<hr>

<h4>Contacts / Notifications</h4>

<div class="">

    <div class="form-group">
        {{ Form::label('branch[telephone]', 'Branch Contact Number', ['class' => 'col-lg-2 control-label']) }}
        <div class="col-lg-10">
            {{ Form::number('branch[telephone]', null, ['class' => 'form-control mobile_input', 'data-minlength'=>'10', 'placeholder' => 'Telephone eg. 0219451234', 'onKeyUp'=> 'if(this.value.length>10) $(this).val(this.value.substr(0, 10));', 'required']) }}
            <div class="help-block with-errors"></div>
        </div><!--col-lg-10-->
    </div><!--form control-->

    <div class="alert alert-info"><i class="fa fa-info-circle"></i> Notifications from {{ config('app.name') }} will be sent to these details.</div>

    <div class="form-group">
        {{ Form::label('branch[notify_email]', 'Branch Email Notifications', ['class' => 'col-lg-2 control-label']) }}
        <div class="col-lg-10">
            {{ Form::email('branch[notify_email]', null, ['class' => 'form-control', 'placeholder' => '', 'required']) }}
            <div class="help-block with-errors"></div>
        </div><!--col-lg-10-->
    </div><!--form control-->

    <div class="form-group">
        {{ Form::label('branch[notify_mobile]', 'Branch Mobile', ['class' => 'col-lg-2 control-label']) }}
        <div class="col-lg-10">
            {{ Form::number('branch[notify_mobile]', null, ['class' => 'form-control mobile_input', 'placeholder' => 'eg. 0821234567', 'data-minlength'=>'10', 'onKeyUp'=> 'if(this.value.length>10) $(this).val(this.value.substr(0, 10));']) }}
        </div><!--col-lg-10-->
    </div><!--form control-->
</div>



<hr>

<h4>Address & Travel</h4>

<div class="form-group">
    {{ Form::label('optArea', 'Branch Location', ['class' => 'col-lg-2 control-label']) }}
    <div class="col-lg-10">

        {{ Form::text('branch[area]', null, ['id' => 'optArea', 'checkme', 'class' => 'form-control input-clean input-lg', 'placeholder' => 'Type area here...', 'required']) }}

        {{ Form::hidden('branch[lat]', null, ['id' => 'lat']) }}
        {{ Form::hidden('branch[lng]', null, ['id' => 'lng']) }}

        @php($gmap_marker['draggable'] = 'true')
        @include('frontend.wizard.custom.geocode', ['address' => isset($professional) && $professional->area, 'field_array'=> 'branch', 'settings' => ['types' => '', 'exclude_fields' => 1]])
    </div><!--col-lg-10-->
</div><!--form control-->

<div class="form-group">
    {{ Form::label('branch[distance_travelled]', 'Willing to travel', ['class' => 'col-lg-2 control-label']) }}
    <div class="col-lg-10">
        {{ Form::select('branch[distance_travelled]', ['0'=>'None','1'=>'1 km','5'=>'5 km','10'=>'10 km','20'=>'20 km','30'=>'30 km','50'=>'50 km','100'=>'100 km','200'=>'200 km'], null, ['class' => 'form-control', 'placeholder' => 'Select a distance', 'required']) }}
        <div class="help-block with-errors"></div>
    </div><!--col-lg-10-->
</div><!--form control-->

resources/views/frontend/professional/includes/form_fields.blade.php
<!-- Tab panes -->

    <div role="tabpanel" class="tab-pane active" id="info">

        <h4>Business Info</h4>

        <div class="form-group">
            {{ Form::label('title', 'Business Title', ['class' => 'col-lg-2 control-label']) }}
            <div class="col-lg-10">
                {{ Form::text('title', null, ['class' => 'form-control', 'placeholder' => 'Title of the business', 'required', 'autocomplete'=>'off']) }}
                <div class="help-block with-errors"></div>
                <div style="display: none" id="company_search" class="suggestresults">
                    <div class="h6 badge label-warning">Claim existing listing:</div>
                    <a onclick="$('#company_search').hide()" href="javascript:void(0)"><i class="fa fa-close fa-lg"></i> close</a>
                </div>
            </div><!--col-lg-10-->
        </div><!--form control-->

        <div class="form-group">
            {{ Form::label('company_name', 'Company Name (If different to title)', ['class' => 'col-lg-2 control-label']) }}
            <div class="col-lg-10">
                {{ Form::text('company_name', null, ['class' => 'form-control', 'placeholder' => 'The registered company name']) }}
                <div class="help-block with-errors"></div>
            </div><!--col-lg-10-->
        </div><!--form control-->

        <div class="form-group">
            {{ Form::label('image', 'Logo', ['class' => 'col-lg-2 control-label', 'accept'=>'image/*']) }}

            <div class="col-lg-10">
                @if(isset($professional))
                    {!! $professional->getLogoHtml('md') !!}
                @endif
                {{ Form::file('logo') }}
            </div><!--col-lg-10-->
        </div><!--form control-->

        <hr>

        <div class="form-group">
            {{ Form::label('company_type', 'Business Type', ['class' => 'col-lg-2 control-label']) }}
            <div class="col-lg-10">
                {{ Form::select('company_type', ['Sole' => 'Sole Trader','CC' => 'Close Corporation','Partnership', 'Private Company' => 'Private Company (PTY LTD)', 'Public Company' => 'Public Company (LTD)', 'Inc' => 'Personal Liability Company', 'Business trust', 'External company', 'Non-Profit'], null, ['class' => 'form-control','id'=> 'company_type', 'placeholder' => 'Select Company Type', 'required']) }}
                <div class="help-block with-errors"></div>
            </div><!--col-lg-10-->
        </div><!--form control-->

        <div class="form-group">
            {{ Form::label('vat_registered', 'VAT Number', ['class' => 'col-lg-2 control-label']) }}
            <div class="col-lg-10">
                {{ Form::text('vat_registered', null, ['class' => 'form-control']) }}
            </div><!--col-lg-10-->
        </div><!--form control-->

        <div class="company_entity_div" style="{{ isset($professional) && $professional->company_type == 'Sole'?'display: none':'' }}">
            <div class="form-group">
                {{ Form::label('company_registration', 'Company Reg No?', ['class' => 'col-lg-2 control-label']) }}
                <div class="col-lg-10">
                    {{ Form::text('company_registration', null, ['class' => 'form-control company_entity', 'placeholder' => '']) }}
                </div><!--col-lg-10-->
            </div><!--form control-->
        </div>

        <div class="soletrader_div" style="{{ isset($professional) && $professional->company_type == 'Sole'?'':'display: none' }}">
            <div class="form-group">
                {{ Form::label('id_number', 'ID number or Work Permit', ['class' => 'col-lg-2 control-label']) }}
                <div class="col-lg-10">
                    {{ Form::text('id_number', null, ['class' => 'form-control soletrader', 'placeholder' => '' ]) }}
                </div><!--col-lg-10-->
            </div><!--form control-->
        </div>

        <hr>

        <div class="form-group">
            {{ Form::label('services', 'Your Services', ['class' => 'col-lg-2 control-label', 'id' => 'services']) }}

            <div class="col-lg-10">
                @include('backend.service.includes.partials.service-list', ['services' => isset($professional) ?$professional->services:null])
            </div><!--col-lg-10-->
        </div><!--form control-->

        <hr>

        <h4>Business Contacts</h4>

        <div class="form-group">
            {{ Form::label('company_email', 'Email', ['class' => 'col-lg-2 control-label']) }}
            <div class="col-lg-10">
                {{ Form::text('company_email', null, ['class' => 'form-control', 'placeholder' => '', 'required']) }}
                <div class="help-block with-errors"></div>
            </div><!--col-lg-10-->
        </div><!--form control-->

        <div class="form-group">
            {{ Form::label('telephone', 'Contact Number', ['class' => 'col-lg-2 control-label']) }}
            <div class="col-lg-10">
                {{ Form::number('telephone', null, ['class' => 'form-control mobile_input', 'data-minlength'=>'10', 'placeholder' => 'Telephone eg. 0219451234', 'onKeyUp'=> 'if(this.value.length>10) $(this).val(this.value.substr(0, 10));', 'required']) }}
                <div class="help-block with-errors"></div>
            </div><!--col-lg-10-->
        </div><!--form control-->

        <div class="form-group">
            {{ Form::label('website_url', 'Website', ['class' => 'col-lg-2 control-label']) }}
            <div class="col-lg-10">
                {{ Form::text('website_url', null, ['class' => 'form-control', 'placeholder' => '']) }}
            </div><!--col-lg-10-->
        </div><!--form control-->

    </div>


    @include('frontend.professional.includes.branches')


    <div role="tabpanel" class="tab-pane" id="profile">
        <h4>Profile</h4>

        <div class="form-group">
            {{ Form::label('description', 'About Us', ['class' => 'col-lg-2 control-label']) }}

            <div class="col-lg-10">
                {{ Form::textarea('description', null, ['class' => 'form-control wysiwyg', 'placeholder' => 'Description', 'required']) }}
                <div class="help-block with-errors"></div>
            </div><!--col-lg-10-->
        </div><!--form control-->


            <hr>

            <div class="form-group">
                {{ Form::label('galleries', 'Photo Gallery', ['class' => 'col-lg-2 control-label']) }}
                <div class="col-lg-10">

                    @if(isset($professional))
                        @include('frontend.media.includes.partials.gallery', ['media' => $professional->media, 'edit' => 1])

                    @endif

                        @include('frontend.media.includes.partials.multi_uploader', ['input_accept'=>'image/*', 'file_mimes' => ['image/jpeg', 'image/png', 'image/gif', 'image/jpg']])

                </div><!--col-lg-10-->
            </div>

            <hr>

            <div class="form-group">
                {{ Form::label('hero_image', 'Header Image', ['class' => 'col-lg-2 control-label', 'accept'=>'image/*']) }}

                <div class="col-lg-10">
                    <p>Upload a large image to be displayed above your profile. Minimum photo width: {{ config('app.images.max_width') }}px</p>

                    @if( isset($professional) && $professional->hero_image_url )
                        <img style="width: 100%" src="{!! $professional->hero_image_url !!}" />
                    @endif
                    {{ Form::file('hero_image') }}
                </div><!--col-lg-10-->
            </div><!--form control-->


    </div>
    <div role="tabpanel" class="tab-pane" id="system">

        <h4>Credentials</h4>
        <div class="form-group">

            <div class="alert alert-info">
                Upload copies of certificates or qualifications that you might have in order to validate your expertise.
                <br/>Eg. Police clearance certificate, Electrical certifications etc.
                <br><b>{{ config('app.name') }} will verify and display the corresponding logo next to your business.</b>
            </div>

            {{ Form::label('resources', 'Resources', ['class' => 'col-lg-2 control-label']) }}
            <div class="col-lg-10">

                @if(isset($professional))

                    @include('frontend.media.includes.partials.gallery', ['media' => $professional->media_resources, 'edit' => 1, 'group'=> 'resources'])

                @endif

                <div class="alert alert-warning"><b>OFFICE USE ONLY:</b> Resource documents not accessible to public or clients.</div>

                @include('frontend.media.includes.partials.multi_uploader', ['group'=> 'resources', 'caption_otions' => ['Certification' => 'Certification', 'Qualification' => 'Qualification', 'License' => 'License', 'PoD' => 'Proof of Address', 'Other' => 'Other']])


            </div><!--col-lg-10-->
        </div>

    </div>

resources/views/frontend/professional/includes/mini_profile.blade.php
<div class="mini-profile">
    <div class="quote-logo pull-left">
        {!! $professional->getLogoHtml('md') !!}
    </div>
    <h3 class="brandname no-margin">
        <a href="{{ route('public.professional.show', [$professional->id, $professional->slug]) }}">{{ $professional->title }} </a> {!! $professional->getVerify('big') !!}
    </h3>

        <div>
            {!!  $professional->recommended_label !!}
        </div>
        <div>
            {!!  $professional->overall_rating_stars !!} <b>{{ $professional->rating_overall_tot }}</b> from {{ isset($professional->stats->reviews_count)?$professional->stats->reviews_count:0  }} Reviews
        </div>

    <div class="padding15"><i class="fa fa-map-marker"></i> {{  $professional->area }}</div>

    <div class="clearfix"></div>

</div>